//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Estudiante
{
    public int Identificacion { get; set; }
    public string Nombre { get; set; }
    public string Primer_Apellido { get; set; }
    public string Segundo_Apellido { get; set; }
    public string CEAD { get; set; }
    public string Programa { get; set; }
    public string Correo { get; set; }
}
